List<String> list1 = [
  "Within twilight's embrace",
  "In the depths of obscurity",
  "Beneath the shroud of night",
  "Through the enigmatic echoes",
  "Amidst the cosmic symphony",
  "Within the sacred enigma",
  "On the threshold of destiny",
  "Between the ancient pillars",
  "In the labyrinth of existence",
  "Under the veiled moon",
  "Amidst the ethereal dance",
  "Through the passage of time",
  "Within the heart's sanctuary",
  "Beneath the tapestry of stars",
  "Within the echoes of silence",
  "Through the river of dreams",
  "In the embrace of the shadows",
  "Within the gaze of constellations",
  "Amidst the realm of dreams",
  "In the silence of creation",
  "Through the threads of fate",
  "Within the tapestry of life",
  "Beneath the embrace of the moon",
  "In the whispered cadence",
  "Through the corridors of time",
  "Within the cosmic tapestry",
  "On the shores of awakening",
  "In the dance of shadows",
  "Through the whispers of destiny",
  "Amidst the ancient whispers",
  "Within the embrace of stars",
  "Beneath the mask of reality",
  "In the depths of introspection",
  "Through the dance of stars",
  "Within the garden's secrets",
  "Amidst the symphony's crescendo",
  "In the depths of the abyss",
  "Under the watchful gaze",
  "In the tapestry of existence",
  "Through the veiled memories",
  "Within twilight's enigma",
];

List<String> list2 = [
  "embrace the arcane wisdom",
  "follow the path of constellations",
  "unveil the hidden truths",
  "seek solace in the depths",
  "emerge as a seeker of mysteries",
  "unravel the intricate threads of destiny",
  "embrace the dance of shadows",
  "emerge as a dreamer of echoes",
  "seek the essence of being",
  "become the guardian of dreams",
  "unveil the enigma of time",
  "find hope amidst the shadows",
  "follow the rhythm of the cosmos",
  "embrace the whispers of fate",
  "emerge as the phoenix of change",
  "unlock the doors of perception",
  "seek the wisdom of ages",
  //"find strength in vulnerability",
  "embrace the cosmic flow",
  "follow the whispers of the heart",
  "emerge from the depths of darkness",
  "seek the light beyond the veils",
  "embrace the dance of transformation",
  "emerge as a traveler of destinies",
  "seek the silent echoes",
  "unveil the truth within the enigma",
  "embrace the intricate path",
  "find courage in the unknown",
  "emerge from the cosmic dance",
  "seek the threads of the universe",
  "embrace the hidden echoes",
  "emerge as a dreamer of stars",
  "find the essence of destiny",
  "seek the light amidst the shadows",
  "embrace the timeless flow",
  "follow the call of the soul",
  "emerge from the depths of oblivion",
  "seek the cosmic whispers of wisdom",
  "embrace the dance of eternal change",
  "follow the echoes of the stars",
  "emerge as a seeker of truth",
  "seek the essence of existence",
];

List<String> list3 = [
  "and let it guide you through the veils",
  "and unveil the secrets of the soul",
  "and find the light within the darkness",
  "and let it resonate with the cosmos",
  "and follow the dance of destiny",
  "and become the guardian of stars",
  "and seek the path of transcendence",
  "and let it echo through the ages",
  "and unveil the mysteries of existence",
  "and find solace in the cosmic void",
  "and let it lead you through the tapestry of time",
  "and follow the whispers of the wind",
  "and become the phoenix of rebirth",
  "and seek the wisdom within the echoes",
  "and let it embrace the essence of your journey",
  "and unveil the tapestry of fate's design",
  "and find the essence of dreams within",
  "and let it weave the song of your destiny",
  "and follow the rhythm of life's dance",
  "and become the echo in the abyss of being",
  "and seek the silent call of the heart",
  "and let it resonate in the stars' symphony",
  "and follow the threads of time",
  "and become the dreamer of cosmic stories",
  "and seek the cosmic embrace of existence",
  "and let it guide you to the unknown horizons",
  "and unveil the truth of your soul",
  "and find hope amidst the shadows' dance",
  "and let it weave the tapestry of your fate",
  "and follow the cosmic echoes through time",
  "and become the weaver of stars' destinies",
  "and seek the mysteries of the enigma within",
];

List<String> startlist = ["Where", "When", "As", "While"];

List<String> subject1 = [
  "The suns",
  "the tigers",
  "the wolves",
  "the stars",
  "the oceans",
  "the winds",
  "the shadows",
  "the moonlit woods",
  "the echoes",
  "the forgotten souls",
  "the ancient stones",
  "the silent birds",
  "the twilight whispers",
  "the restless rivers",
  "the midnight dreams",
  "the wandering spirits",
  "the silver clouds",
  "the elusive thoughts",
  "the silent ruins",
  "the fading embers",
  "the forgotten melodies",
  "the eternal flames",
  "the enigmatic riddles",
  "the elusive phantoms",
  "the ethereal mists",
  "the unseen paths",
  "the elusive echoes",
  "the whispering winds",
  "the veiled moon",
  "the veiled night",
  "the nameless stars",
  "the endless void",
  "the timeless echoes",
  "the silent steps",
  "the hidden desires",
  "the fleeting memories",
  "the secret chambers",
  "the unspoken words",
  "the sacred whispers",
  "the ancient spells",
  "the elusive shadows",
  "the mystic secrets",
  "the forgotten tales",
  "the lost constellations",
  "the silent hearts",
  "the veiled enchantments",
  "the wandering gazes",
  "the veiled dreams",
  "the hidden chambers",
  "the fading echoes",
  "the eternal questions",
  "the timeless wanderers",
  "the veiled serenity",
  "the distant echoes",
  "the hidden treasures",
  "the forgotten songs",
  "the silent prayers",
  "the elusive stars",
  "the nameless whispers",
  "the elusive echoes",
  "the ethereal visions",
  "the timeless melodies",
  "the eternal skies",
  "the elusive paths",
  "the fading light",
  "the enigmatic verses",
  "the veiled horizons",
  "the forgotten memories",
  "the sacred echoes",
  "the wandering souls",
  "the ancient symbols",
  "the veiled abyss",
  "the silent echoes",
  "the ethereal moonlight",
  "the timeless echoes",
  "the hidden realms",
  "the fading echoes",
  "the elusive symphonies",
  "the veiled whispers",
  "the sacred rhythms",
  "the wandering stars",
  "the forgotten tales",
  "the endless nights",
  "the enigmatic dances",
  "the elusive mysteries",
  "the veiled echoes",
  "the eternal flames",
  "the hidden desires",
  "the timeless enchantments",
  "the silent echoes",
  "the nameless destinies",
  "the elusive echoes",
  "the ethereal journeys",
  "the fading echoes",
  "the veiled symphonies",
  "the sacred echoes",
  "the wandering winds",
  "the ancient verses",
  "the veiled melodies",
  "the forgotten echoes",
  "the endless horizons",
  "the mystical dreams",
  "the elusive galaxies",
  "the veiled worlds",
  "the silent echoes",
  "the timeless echoes",
  "the hidden stories",
  "the sacred shadows",
  "the wandering echoes",
  "the ethereal voices",
  "the veiled stars"
];

List<String> verb1 = [
  "chase",
  "seek",
  "hide from",
  "greet",
  "whisper to",
  "dance with",
  "embrace",
  "follow",
  "enchant",
  "speak to",
  "wander with",
  "embrace",
  "unravel",
  "mingle with",
  "touch",
  "gaze upon",
  "befriend",
  "surrender to",
  "become one with",
  "traverse",
  "converse with",
  "awaken",
  "unveil",
  "ponder",
  "wander through",
  "explore",
  "imbibe",
  "unravel",
  "journey with",
  //"unveil the secrets of",
  "immerse in",
  "listen to",
  "linger in",
  "unlock",
  "witness",
  //"whisper the tales of",
  //"inquire of",
  "dream of",
  "reflect upon",
  "become",
  "navigate through",
  "commune with",
  "ponder upon",
  "delve into",
  "linger amidst",
  //"immerse in the whispers of",
  //"traverse the paths of",
  "envelop in",
  "behold",
  "journey amidst",
  //"unveil the hidden truths of",
  //"immerse in the echoes of",
  "find solace in",
  //"absorb the essence of",
  //"unravel the threads of",
  "awaken amidst",
  "dance amidst",
  "linger within",
];

List<String> object1 = [
  "ancient maps and compasses",
  "hidden paths beneath trees",
  "fading ink on yellowed pages",
  "scent of rain on city streets",
  "laughter in crowded cafes",
  "flames dancing in the fireplace",
  "wind through fields of wheat",
  "pebbles skipping on water's surface",
  "chatter of voices in busy markets",
  "footprints on sand, memories of the sea",
  "whispers of a wind-carried story",
  "colors blending on the canvas",
  "stardust in the vast night sky",
  "echoes of a moonlight lullaby",
  "crackling logs and crackling thoughts",
  "sails catching the ocean breeze",
  "buzzing of bees among wildflowers",
  "glimpses of stars through city lights",
  "ripples on the surface of a pond",
  "footprints on mountain trails",
  "footsteps in the snow",
  "whispers of ancient trees in forests",
  "fragments of dreams within cloud formations",
  "echoes of birdsongs",
  "echoes of footsteps on cobblestone streets",
  "past sunsets over open horizons",
  "grains of soft desert sand",
  "shadows of leaves dancing in sunlight",
  "stories carried by ocean waves",
  "sounds of hidden waterfalls",
  "chimes of church bells in the distance",
  "flashes of lightning in stormy skies",
  "fragments of laughter from distant hills",
  //"traces of footsteps on moss-covered rocks",
  //"glimpses of moonlight on forest paths",
  "crumbling ruins and whispered history",
  "moments frozen in the photographer's lens",
  "embers of campfires and conversations",
  //"footprints fading into the sands of time",
  "whispered breaths of love",
  "echoes of thunder",
  "glimpses of the night",
  "footprints on city sidewalks",
  "shadows of birds soaring"
];

List<String> subject2 = [
  "You",
  "He",
  "She",
  "THe things you desire",
  "They",
  "We",
  "The things you fear"
];

List<String> verb21 = ["shall", "must", "will", "won't", "must not"];

List<String> verb22 = [
  "walk on",
  "love",
  "linger in",
  "embrace",
  "unravel",
  "mingle with",
  "touch",
  "gaze upon",
  "befriend",
  "surrender to",
  "become one with",
  "traverse",
  "converse with",
  "awaken",
  "unlock",
  "witness",
  "whisper the tales of",
  "inquire of",
  "dream of",
  "reflect upon",
  "become",
  "navigate through",
  "embrace the essence of",
  "commune with",
  "ponder upon",
  "delve into",
  "journey",
  "ponder",
  "wander",
  "gaze",
  "whisper",
  "embrace",
  "savor",
  "reflect",
  "relinquish",
  "unravel",
  "unfold",
  "transcend",
  "contemplate",
  "unveil",
  "immerse",
  "awaken",
  "emerge from",
  "ascend",
  "linger",
  "reside",
  "dissolve",
  "stir",
  "navigate",
  "perceive",
  "surrender",
  "explore",
  "illuminate",
  "reverberate",
  "radiate",
  "absorb",
  "attune",
  "converge",
  "transpire",
  "meld",
  "echo",
  "whirl",
  "breathe",
  "expand",
  "weave",
  "intertwine",
  "imbibe",
  "envelop",
  "witness",
  "pierce",
  "cradle",
  "merge",
  "linger",
  "wade",
  "awaken",
  "reverberate",
  "resonate",
  "immerse",
  "traverse",
  "fathom",
  "ascend",
  "journey",
  "converse",
  "absorb",
  "transcend",
  "illuminate",
  "bask",
  "navigate",
  "unveil",
  "unwind",
  "whisper",
  "unearth",
  "emerge into",
  "converge",
  "reflect",
  "attune",
  "pulsate",
  "unfold",
  "imbue",
  "glimpse",
  "savor",
  "transcend",
  "intertwine",
  "relinquish",
  "surrender to",
  "reside",
  "ripple",
  "absorb",
  "immerse",
  "breathe",
  "reverberate",
  "explore",
  "weave",
  "journey",
  "converse",
  "whisper",
  "stir",
  "awaken",
  "gaze",
  "ascend",
  "unravel",
  "unveil",
  "wander",
  "reflect",
  "navigate",
  "contemplate",
  "journey in",
  "ponder on",
  "wander through",
  "gaze into",
  "whisper to",
  "embrace in",
  "savor at",
  "reflect on",
  "relinquish to",
  "unravel in",
  "unfold from",
  "transcend beyond",
  "contemplate at",
  "unveil",
  "immerse in",
  "awaken to",
  "emerge from",
  "ascend to",
  "linger in",
  "reside within",
  "dissolve into",
  "stir within",
  "navigate through",
  "perceive beyond",
  "explore",
  "illuminate the depths of",
  "reverberate within",
  "radiate from",
  "absorb the essence of",
  "attune to",
  "converge towards",
  "transpire through",
  "meld with",
  "echo across",
  "whirl in",
  "breathe in",
  "expand into",
  "weave through",
  "intertwine with",
  "imbibe from",
  "envelop in",
  "witness at",
  "pierce through",
  "cradle in",
  "merge with",
  "linger in",
  "wade through",
  "awaken to",
  "reverberate in",
  "resonate with",
  "immerse in",
  "traverse through",
  "fathom in",
  "ascend to",
  "journey into",
  "converse with",
  "absorb from",
  "transcend to",
  "illuminate with",
  "bask in",
  "navigate through",
  "unveil",
  "unwind in",
  "whisper to",
  "unearth from",
  "emerge from",
  "converge towards",
  "reflect on",
  "attune to",
  "pulsate within",
  "unfold from",
  "imbue with",
  "glimpse into",
  "savor at",
  "transcend to",
  "intertwine with",
  "relinquish to",
  "reside in",
  "ripple through",
  "absorb from",
  "immerse in",
  "breathe in",
  "reverberate within",
  "explore",
  "weave through",
  "journey into",
  "converse with",
  "whisper to",
  "stir within",
  "awaken to",
  "gaze into",
  "ascend to",
  "unravel in",
  "unveil",
  "wander through",
  "reflect on",
  "navigate through",
  "contemplate at",
];

List<String> object2 = [
  "whispers carried by the breeze",
  "a flickering candle's glow",
  "echoes of footsteps on cobblestone",
  "the scent of morning rain",
  "a sunbeam through parted clouds",
  "a leaf's gentle descent to earth",
  "a river's reflection of the sky",
  "a bird's melody at dawn",
  "the touch of dew-kissed petals",
  "a forgotten letter in a dusty drawer",
  "the taste of salt in ocean air",
  "a rustling in the autumn leaves",
  "the warmth of a well-worn book",
  "the embrace of a sunlit meadow",
  "a single raindrop's journey",
  "the first star's distant twinkle",
  "a whispered secret shared at night",
  "the echo of laughter in a crowded room",
  "a shadow cast by the setting sun",
  "a river's journey to the sea",
  "the touch of a lover's hand",
  "a forgotten trail through the woods",
  "the dance of flames in a fireplace",
  "a key turning in an old lock",
  "a ripple in a tranquil pond",
  "a sigh carried on the wind",
  "a melody hummed in solitude",
  "the silence after a passing storm",
  "a fragrance carried by a passing stranger",
  "a horizon painted with colors of dusk",
  "a mirror reflecting a fleeting moment",
  "a single word spoken in the dark",
  "a path winding through the city's heart",
  "a memory triggered by a familiar scent",
  "a question that lingers in the air",
  "a bridge spanning a gentle stream",
  "a map folded and worn from travels",
  "a shadow cast by a streetlamp's light",
  "a keychain with stories to tell",
  "a pebble's splash in a clear pond",
  "a whisper exchanged between friends",
  "an echo bouncing off canyon walls",
  "a touch that ignites a spark",
  "a secret shared under the moon",
  "a reflection in a polished mirror",
  "a chapter unfinished in the book of life",
  "a name whispered on the breeze",
  "a path leading to hidden treasures",
  "a shadow growing longer at sunset",
  "a key that opens unseen doors",
  "a ripple expanding on a calm lake",
  "a promise woven into the stars",
  "a melody carried by the wind",
  "silence following the night's song",
  "a scent that evokes memories",
  "the horizon where dreams awaken",
  "a mirror reflecting the soul's depths",
  "a final word before the dawn",
  "a path guiding the curious traveler",
  "a touch that kindles forgotten fires",
  "an answer to the heart's unspoken question"
];
